package com.smartqueue.backend.service;

import com.lowagie.text.*;
import com.lowagie.text.pdf.*;
import com.smartqueue.backend.entity.DoctorAssignmentHistory;
import com.smartqueue.backend.entity.Patient;
import com.smartqueue.backend.entity.Token;
import com.smartqueue.backend.repository.DoctorRepository;
import com.smartqueue.backend.repository.PatientRepository;
import com.smartqueue.backend.repository.TokenRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * Phase 4 — Medical Report Generation (OpenPDF).
 *
 * Generates a secure, locally-rendered PDF containing:
 *  - Patient demographics
 *  - Current token / visit details
 *  - Full doctor assignment history (continuity of care audit)
 *
 * All processing is local — no external PDF service calls.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class MedicalReportService {

    private final PatientRepository patientRepository;
    private final TokenRepository tokenRepository;
    private final DoctorRepository doctorRepository;
    private final ContinuityOfCareService continuityOfCareService;

    private static final DateTimeFormatter DT_FMT =
            DateTimeFormatter.ofPattern("dd MMM yyyy, HH:mm");

    // ── Brand colours ──────────────────────────────────────────────────────
    private static final Color PRIMARY   = new Color(0x1A, 0x73, 0xE8);   // SmartQueue blue
    private static final Color ACCENT    = new Color(0x34, 0xA8, 0x53);   // green
    private static final Color LIGHT_BG  = new Color(0xF1, 0xF3, 0xF4);
    private static final Color TEXT_DARK = new Color(0x20, 0x21, 0x24);

    // ── Fonts (built-in Helvetica to avoid font-file deps) ─────────────────
    private static final Font TITLE_FONT   = new Font(Font.HELVETICA, 20, Font.BOLD,   PRIMARY);
    private static final Font HEADING_FONT = new Font(Font.HELVETICA, 12, Font.BOLD,   Color.WHITE);
    private static final Font LABEL_FONT   = new Font(Font.HELVETICA, 10, Font.BOLD,   TEXT_DARK);
    private static final Font VALUE_FONT   = new Font(Font.HELVETICA, 10, Font.NORMAL, TEXT_DARK);
    private static final Font SMALL_FONT   = new Font(Font.HELVETICA,  8, Font.ITALIC, Color.GRAY);

    /**
     * Generates a PDF visit summary for the given token.
     *
     * @param tokenId the token whose report is requested
     * @return raw PDF bytes ready for HTTP streaming
     */
    public byte[] generateVisitReport(Long tokenId) {
        Token token = tokenRepository.findByIdWithPatient(tokenId)
                .orElseThrow(() -> new IllegalArgumentException("Token not found: " + tokenId));

        Patient patient = token.getPatient();
        if (patient == null) {
            throw new IllegalStateException("Token " + tokenId + " has no associated patient");
        }

        List<DoctorAssignmentHistory> history =
                continuityOfCareService.getPatientHistory(patient.getId());

        try (ByteArrayOutputStream bos = new ByteArrayOutputStream()) {

            Document doc = new Document(PageSize.A4, 50, 50, 60, 50);
            PdfWriter writer = PdfWriter.getInstance(doc, bos);

            // ── Header/Footer event ────────────────────────────────────────
            writer.setPageEvent(new ReportPageEvent());

            doc.open();

            // ── 1. Clinic banner ──────────────────────────────────────────
            addClinicBanner(doc);

            // ── 2. Section: Patient Demographics ─────────────────────────
            addSectionHeader(doc, "PATIENT INFORMATION");
            addDemographicsTable(doc, patient);

            doc.add(Chunk.NEWLINE);

            // ── 3. Section: Current Visit ─────────────────────────────────
            addSectionHeader(doc, "CURRENT VISIT");
            addVisitTable(doc, token);

            doc.add(Chunk.NEWLINE);

            // ── 4. Section: Visit History ─────────────────────────────────
            if (!history.isEmpty()) {
                addSectionHeader(doc, "VISIT HISTORY (" + history.size() + " records)");
                addHistoryTable(doc, history);
            }

            // ── 5. Footer disclaimer ──────────────────────────────────────
            doc.add(Chunk.NEWLINE);
            Paragraph disclaimer = new Paragraph(
                    "This document is auto-generated by SmartQueue PMS. " +
                    "For clinical decisions, consult the treating physician.",
                    SMALL_FONT);
            disclaimer.setAlignment(Element.ALIGN_CENTER);
            doc.add(disclaimer);

            doc.close();

            log.info("PDF report generated: tokenId={} patientId={}", tokenId, patient.getId());
            return bos.toByteArray();

        } catch (Exception e) {
            log.error("PDF generation failed for tokenId={}: {}", tokenId, e.getMessage(), e);
            throw new RuntimeException("Failed to generate medical report", e);
        }
    }

    // ── Private builders ───────────────────────────────────────────────────

    private void addClinicBanner(Document doc) throws DocumentException {
        Paragraph title = new Paragraph("SmartQueue Health System", TITLE_FONT);
        title.setAlignment(Element.ALIGN_CENTER);
        doc.add(title);

        Paragraph sub = new Paragraph("Visit Summary Report", new Font(Font.HELVETICA, 12, Font.NORMAL, Color.GRAY));
        sub.setAlignment(Element.ALIGN_CENTER);
        doc.add(sub);

        doc.add(new Paragraph(" "));

        // Divider
        PdfPTable divider = new PdfPTable(1);
        divider.setWidthPercentage(100);
        PdfPCell line = new PdfPCell();
        line.setBackgroundColor(PRIMARY);
        line.setFixedHeight(3f);
        line.setBorder(Rectangle.NO_BORDER);
        divider.addCell(line);
        doc.add(divider);
        doc.add(new Paragraph(" "));
    }

    private void addSectionHeader(Document doc, String title) throws DocumentException {
        PdfPTable table = new PdfPTable(1);
        table.setWidthPercentage(100);
        PdfPCell cell = new PdfPCell(new Phrase(title, HEADING_FONT));
        cell.setBackgroundColor(PRIMARY);
        cell.setPadding(6f);
        cell.setBorder(Rectangle.NO_BORDER);
        table.addCell(cell);
        doc.add(table);
    }

    private void addDemographicsTable(Document doc, Patient patient) throws DocumentException {
        PdfPTable table = new PdfPTable(4);
        table.setWidthPercentage(100);
        table.setWidths(new float[]{1.2f, 2f, 1.2f, 2f});

        addRow(table, "Name",   patient.getName(),
                       "Patient ID", String.valueOf(patient.getId()));
        addRow(table, "Age",    patient.getAge() != null ? patient.getAge() + " yrs" : "—",
                       "Gender", patient.getGender() != null ? patient.getGender() : "—");
        addRow(table, "Phone",  patient.getPhone() != null ? patient.getPhone() : "—",
                       "Blood Group", patient.getBloodGroup() != null ? patient.getBloodGroup() : "—");
        addRow(table, "ABHA ID", patient.getAbhaId() != null ? patient.getAbhaId() : "—",
                       "Registered", patient.getCreatedAt() != null
                               ? patient.getCreatedAt().format(DT_FMT) : "—");

        doc.add(table);
    }

    private void addVisitTable(Document doc, Token token) throws DocumentException {
        PdfPTable table = new PdfPTable(4);
        table.setWidthPercentage(100);
        table.setWidths(new float[]{1.5f, 2f, 1.5f, 2f});

        String doctorName = "—";
        if (token.getDoctorId() != null) {
            doctorName = doctorRepository.findById(token.getDoctorId())
                    .map(d -> d.getName() + " (" + d.getSpecialization() + ")")
                    .orElse("Unknown");
        }

        addRow(table, "Token No.",  token.getTokenNumber(),
                       "Status",     token.getStatus().name());
        addRow(table, "Service",    token.getServiceType() != null ? token.getServiceType().name() : "—",
                       "Visit Type", token.getVisitType() != null ? token.getVisitType().name() : "—");
        addRow(table, "Doctor",     doctorName,
                       "Severity",   token.getSeverityScore() != null ? String.valueOf(token.getSeverityScore()) : "—");
        addRow(table, "Chief Complaint",
                       token.getChiefComplaint() != null ? token.getChiefComplaint() : "—",
                       "Created",    token.getCreatedAt() != null ? token.getCreatedAt().format(DT_FMT) : "—");

        if (token.getConsultationStart() != null) {
            addRow(table, "Consult Start", token.getConsultationStart().format(DT_FMT),
                           "Consult End",  token.getConsultationEnd() != null
                                   ? token.getConsultationEnd().format(DT_FMT) : "Ongoing");
        }

        doc.add(table);
    }

    private void addHistoryTable(Document doc, List<DoctorAssignmentHistory> history) throws DocumentException {
        PdfPTable table = new PdfPTable(5);
        table.setWidthPercentage(100);
        table.setWidths(new float[]{1.8f, 2.2f, 1.5f, 1.5f, 3f});

        // Column headers
        String[] headers = {"Date", "Doctor", "Specialization", "Visit Type", "Chief Complaint"};
        for (String h : headers) {
            PdfPCell hCell = new PdfPCell(new Phrase(h, new Font(Font.HELVETICA, 9, Font.BOLD, Color.WHITE)));
            hCell.setBackgroundColor(ACCENT);
            hCell.setPadding(5f);
            hCell.setBorder(Rectangle.NO_BORDER);
            table.addCell(hCell);
        }

        boolean alternate = false;
        for (DoctorAssignmentHistory entry : history) {
            Color rowBg = alternate ? LIGHT_BG : Color.WHITE;
            alternate   = !alternate;

            String doctorName = doctorRepository.findById(entry.getDoctorId())
                    .map(d -> d.getName()).orElse("Dr. #" + entry.getDoctorId());

            addHistoryRow(table, rowBg,
                    entry.getAssignedAt() != null ? entry.getAssignedAt().format(DT_FMT) : "—",
                    doctorName,
                    entry.getSpecialization() != null ? entry.getSpecialization() : "—",
                    entry.getVisitType()       != null ? entry.getVisitType()       : "—",
                    entry.getChiefComplaint()  != null ? entry.getChiefComplaint()  : "—"
            );
        }

        doc.add(table);
    }

    // ── Cell helpers ───────────────────────────────────────────────────────

    private void addRow(PdfPTable table, String label1, String val1, String label2, String val2) {
        table.addCell(labelCell(label1));
        table.addCell(valueCell(val1));
        table.addCell(labelCell(label2));
        table.addCell(valueCell(val2));
    }

    private void addHistoryRow(PdfPTable table, Color bg, String... values) {
        for (String v : values) {
            PdfPCell cell = new PdfPCell(new Phrase(v, VALUE_FONT));
            cell.setBackgroundColor(bg);
            cell.setPadding(4f);
            cell.setBorder(Rectangle.BOTTOM);
            cell.setBorderColor(new Color(0xE0, 0xE0, 0xE0));
            table.addCell(cell);
        }
    }

    private PdfPCell labelCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text, LABEL_FONT));
        cell.setBackgroundColor(LIGHT_BG);
        cell.setPadding(5f);
        cell.setBorder(Rectangle.BOTTOM);
        cell.setBorderColor(new Color(0xE0, 0xE0, 0xE0));
        return cell;
    }

    private PdfPCell valueCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text != null ? text : "—", VALUE_FONT));
        cell.setPadding(5f);
        cell.setBorder(Rectangle.BOTTOM);
        cell.setBorderColor(new Color(0xE0, 0xE0, 0xE0));
        return cell;
    }

    // ── Page header/footer ─────────────────────────────────────────────────

    private static class ReportPageEvent extends PdfPageEventHelper {
        @Override
        public void onEndPage(PdfWriter writer, Document document) {
            PdfContentByte cb = writer.getDirectContent();
            Phrase footer = new Phrase(
                    "SmartQueue PMS  |  Confidential  |  Page " + writer.getPageNumber(),
                    new Font(Font.HELVETICA, 8, Font.NORMAL, Color.GRAY));
            ColumnText.showTextAligned(cb, Element.ALIGN_CENTER, footer,
                    (document.left() + document.right()) / 2,
                    document.bottom() - 10, 0);
        }
    }
}
